In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

In [142]:
from sdia_python.lab2.box_window import BoxWindow, UnitBoxWindow
from sdia_python.lab2.ball_window import BallWindow




In [129]:
c=BoxWindow(np.array([[0, 5], [-1.45, 3.14], [-10, 10]]))
print(c.bounds)

[[  0.     5.  ]
 [ -1.45   3.14]
 [-10.    10.  ]]


In [133]:
c.rand(3)

array([[ 5.        ,  0.92586234, -1.68742581],
       [ 5.        ,  2.71137418, -8.65977135],
       [ 5.        , -0.52795213, -5.93207918]])

In [115]:
np.random.uniform(1,2)

1.091468188339448

In [135]:
np.array([1, 1, 1]).shape

(3,)

In [101]:
np.random.random_sample(1)

array([0.18430185])

In [140]:
c=UnitBoxWindow(np.array([2, 3]), 2)
print(c.bounds)

[[1.5 2.5]
 [2.5 3.5]]


In [144]:
c=BallWindow(np.array([[0, 5]]),1)


In [146]:
c.center

array([[0, 5]])

In [147]:
c.radius

1

In [145]:
[np.random.uniform(a - b, a + b) for (a, b) in (c.center, c.radius)]

ValueError: not enough values to unpack (expected 2, got 1)